config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Check this
  # http://blog.railsupgrade.com/2014/05/how-to-override-devise-default-routes.html

  devise_for :users,
             :controllers => { :registrations => 'registrations', :confirmations => 'confirmations',
                               :sessions => 'sessions' },
             path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :entries do
    resources :reports
    member do
      put 'upvote'
      put 'unupvote'
      put 'downvote'
      put 'undownvote'
      put 'save_entry'
      put 'unsave_entry'
      put 'verify'
      put 'unverify'
    end
  end

  match 'help', to: 'messages#new', :via => 'get'
  resources :messages, only: [:create]

  root 'entries#index'
  match 'reports', to: 'flags#index', :via => 'get'
  match 'search', to: 'pages#search', :via => 'get'
  match 'trending', to: 'pages#trending', :via => 'get'
  match 'users', to: 'pages#users', :via => 'get'
  match 'verify', to: 'pages#verify', :via => 'get'
  match 'about', to: 'pages#about', :via => 'get'
  match 'privacy', to: 'pages#privacy', :via => 'get'
  match 'terms', to: 'pages#terms', :via => 'get'
  match 'guidelines', to: 'pages#guidelines', :via => 'get'
  match 'competition', to: 'pages#competition', :via => 'get'

  # Make sure profile routes are always last to allow mis-routing
  # See https://stackoverflow.com/questions/16796244/rails-username-in-url
  get ':username', to: 'profiles#show', as: :profile
  get ':username/votes', to: 'profiles#votes', as: :votes
  get ':username/saved', to: 'profiles#saved', as: :saved
  get ':username/verified', to: 'profiles#verified', as: :verified
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user
  before_action :require_username

  def show
    if @user
      custom_meta_tags("@#{ @user.username }'s Timeline",
                       "Translations created by @#{ @user.username }.",
                       ["#{ @user.username }", "learn", "oshiwambo"])

      @entries = @user.entries.order(created_at: :desc).page params[:page]
    end
  end

  def votes
    custom_meta_tags("@#{ @user.username }'s Votes",
                     "Translations voted by @#{ @user.username }.",
                     ["#{ @user.username }", "votes", "learn", "oshiwambo"])

    @entries = (@user.get_voted Entry, :vote_scope => 'vote').page params[:page]
  end

  def saved
    custom_meta_tags("@#{ @user.username }'s Bookmarks",
                     "Translations created by @#{ @user.username }.",
                     ["#{ @user.username }", "saved", "bookmarks", "learn", "oshiwambo"])

    @entries = (@user.get_voted Entry, :vote_scope => 'saved').page params[:page]
  end

  def verified
    custom_meta_tags("@#{ @user.username }'s Verified",
                     "Translations verified by @#{ @user.username }.",
                     ["#{ @user.username }", "verified", "learn", "oshiwambo"])

    @entries = (@user.get_voted Entry, :vote_scope => 'verify').page params[:page]
  end

  private

  def set_user
    @user = User.find_by(username: params[:username])
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_user_not_found.html.erb
<!--suppress CheckTagEmptyBody -->
<div class="row">
  <div class="col-xs-12 ">
    <nav>
      <div class="nav p-0 nav-tabs nav-fill" id="nav-tab" role="tablist">
        <%= link_to users_path, class: "remove-webkit btn nav-link text-secondary active profile-tab-btn", type: "button" do %>
          <strong>Entries</strong>
        <% end %>

        <%= link_to users_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
          <strong>Votes</strong>
        <% end %>

        <%= link_to users_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
          <strong>Saved</strong>
        <% end %>
      </div>
    </nav>
    <div class="tab-content" id="nav-tabContent" style="padding-top: 1em">
      <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
        <h5 class="text-secondary text-center">
          This user doesn't exist
        </h5>
        <p class="text-secondary text-center" style="font-size: 0.8em">
          Try <%= link_to "searching", users_path, class: "text-yellow text-decoration-none" %> for another.
        </p>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/profiles/saved.html.erb
<!--suppress CheckTagEmptyBody -->
<div class="row">
  <div class="col-xs-12 ">
    <nav>
      <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
        <%= link_to profile_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
          <strong>Entries</strong>
        <% end %>

        <%= link_to votes_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
          <strong>Votes</strong>
        <% end %>

        <%= link_to saved_path, class: "remove-webkit btn nav-link text-secondary active profile-tab-btn", type: "button" do %>
          <strong>Saved</strong>
        <% end %>

        <% if @user.moderator? %>
          <%= link_to verified_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
            <strong>Verified</strong>
          <% end %>
        <% end %>
      </div>
    </nav>
    <div class="tab-content" id="nav-tabContent" style="padding-top: 1em">
      <div class="tab-pane fade show active" id="nav-saved" role="tabpanel" aria-labelledby="nav-saved-tab">
        <p class="text-secondary text-left">
          <%= link_to '@' + @user.username, profile_path(@user),
                      class: 'text-decoration-none text-secondary' %>
          <%= is_moderator(@user) %>
        </p>
        <div id="entries-wrap">
          <%= render 'entries/index' %>
        </div>
        <div id="load-more-entries" class="text-center">
          <%= link_to_next_page @entries, 'load more', remote: true,
                                class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>
        </div>
        <br>
      </div>
    </div>
  </div>
</div>
<br>

<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    })

    var triggerTabList = [].slice.call(document.querySelectorAll('#myTab a'))
    triggerTabList.forEach(function (triggerEl) {
        var tabTrigger = new bootstrap.Tab(triggerEl)

        triggerEl.addEventListener('click', function (event) {
            event.preventDefault()
            tabTrigger.show()
        })
    })
</script>

app/views/profiles/saved.js.erb
$("#entries-wrap").append("<%= escape_javascript(render partial: 'entries/index') %>")
$("#load-more-entries").html("<%=j link_to_next_page @entries, 'load more', remote: true,
                                   class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>")

app/views/profiles/show.html.erb
<!--suppress CheckTagEmptyBody -->
<% if not @entries %>
  <%= render 'profiles/user_not_found' %>
<% else %>
  <div class="row">
    <div class="col-xs-12 ">
      <nav>
        <div class="nav p-0 nav-tabs nav-fill" id="nav-tab" role="tablist">
          <%= link_to profile_path, class: "remove-webkit btn nav-link text-secondary active profile-tab-btn", type: "button" do %>
            <strong>Entries</strong>
          <% end %>

          <%= link_to votes_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
            <strong>Votes</strong>
          <% end %>

          <%= link_to saved_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
            <strong>Saved</strong>
          <% end %>

          <% if @user.moderator? %>
            <%= link_to verified_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
              <strong>Verified</strong>
            <% end %>
          <% end %>
        </div>
      </nav>
      <div class="tab-content" id="nav-tabContent" style="padding-top: 1em">
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
          <p class="text-secondary">
            <%= @user.entries_count %> created |
            <%= link_to '@' + @user.username, profile_path(@user),
                        class: 'text-decoration-none text-secondary' %>
            <%= is_moderator(@user) %>
          </p>
          <div id="entries-wrap">
            <%= render 'entries/index' %>
          </div>
          <div id="load-more-entries" class="text-center">
            <%= link_to_next_page @entries, 'load more', remote: true,
                                  class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>
          </div>
          <br>
        </div>
      </div>
    </div>
  </div>
<% end %>
<br>

<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    })

    var triggerTabList = [].slice.call(document.querySelectorAll('#myTab a'))
    triggerTabList.forEach(function (triggerEl) {
        var tabTrigger = new bootstrap.Tab(triggerEl)

        triggerEl.addEventListener('click', function (event) {
            event.preventDefault()
            tabTrigger.show()
        })
    })
</script>

app/views/profiles/show.js.erb
$("#entries-wrap").append("<%= escape_javascript(render partial: 'entries/index') %>")
$("#load-more-entries").html("<%=j link_to_next_page @entries, 'load more', remote: true,
                                   class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>")

app/views/profiles/verified.html.erb
<!--suppress CheckTagEmptyBody -->
<div class="row">
  <div class="col-xs-12 ">
    <nav>
      <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
        <%= link_to profile_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
          <strong>Entries</strong>
        <% end %>

        <%= link_to votes_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
          <strong>Votes</strong>
        <% end %>

        <%= link_to saved_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
          <strong>Saved</strong>
        <% end %>

        <% if @user.moderator? %>
          <%= link_to verified_path, class: "remove-webkit btn nav-link text-secondary active profile-tab-btn", type: "button" do %>
            <strong>Verified</strong>
          <% end %>
        <% end %>
      </div>
    </nav>
    <div class="tab-content" id="nav-tabContent" style="padding-top: 1em">
      <div class="tab-pane fade show active" id="nav-reviewed" role="tabpanel" aria-labelledby="nav-reviewed-tab">
        <p class="text-secondary text-left">
          <%= link_to '@' + @user.username, profile_path(@user),
                      class: 'text-decoration-none text-secondary' %>
          <%= is_moderator(@user) %>
        </p>
        <div id="entries-wrap">
          <%= render 'entries/index' %>
        </div>
        <div id="load-more-entries" class="text-center">
          <%= link_to_next_page @entries, 'load more', remote: true,
                                class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>
        </div>
        <br>
      </div>
    </div>
  </div>
</div>
<br>

<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    })

    var triggerTabList = [].slice.call(document.querySelectorAll('#myTab a'))
    triggerTabList.forEach(function (triggerEl) {
        var tabTrigger = new bootstrap.Tab(triggerEl)

        triggerEl.addEventListener('click', function (event) {
            event.preventDefault()
            tabTrigger.show()
        })
    })
</script>

app/views/profiles/verified.js.erb
$("#entries-wrap").append("<%= escape_javascript(render partial: 'entries/index') %>")
$("#load-more-entries").html("<%=j link_to_next_page @entries, 'load more', remote: true,
                                   class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>")

app/views/profiles/votes.html.erb
<!--suppress CheckTagEmptyBody -->
<div class="row">
  <div class="col-xs-12 ">
    <nav>
      <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
        <%= link_to profile_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
          <strong>Entries</strong>
        <% end %>

        <%= link_to votes_path, class: "remove-webkit btn nav-link text-secondary active profile-tab-btn", type: "button" do %>
          <strong>Votes</strong>
        <% end %>

        <%= link_to saved_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
          <strong>Saved</strong>
        <% end %>

        <% if @user.moderator? %>
          <%= link_to verified_path, class: "remove-webkit btn nav-link text-secondary profile-tab-btn", type: "button" do %>
            <strong>Verified</strong>
          <% end %>
        <% end %>
      </div>
    </nav>
    <div class="tab-content" id="nav-tabContent" style="padding-top: 1em">
      <div class="tab-pane fade show active" id="nav-reviewed" role="tabpanel" aria-labelledby="nav-reviewed-tab">
        <p class="text-secondary text-left">
          <%= link_to '@' + @user.username, profile_path(@user),
                      class: 'text-decoration-none text-secondary' %>
          <%= is_moderator(@user) %>
        </p>
        <div id="entries-wrap">
          <%= render 'entries/index' %>
        </div>
        <div id="load-more-entries" class="text-center">
          <%= link_to_next_page @entries, 'load more', remote: true,
                                class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>
        </div>
        <br>
      </div>
    </div>
  </div>
</div>
<br>

<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    })

    var triggerTabList = [].slice.call(document.querySelectorAll('#myTab a'))
    triggerTabList.forEach(function (triggerEl) {
        var tabTrigger = new bootstrap.Tab(triggerEl)

        triggerEl.addEventListener('click', function (event) {
            event.preventDefault()
            tabTrigger.show()
        })
    })
</script>

app/views/profiles/votes.js.erb
$("#entries-wrap").append("<%= escape_javascript(render partial: 'entries/index') %>")
$("#load-more-entries").html("<%=j link_to_next_page @entries, 'load more', remote: true,
                                   class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>")