config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Check this
  # http://blog.railsupgrade.com/2014/05/how-to-override-devise-default-routes.html

  devise_for :users,
             :controllers => { :registrations => 'registrations', :confirmations => 'confirmations',
                               :sessions => 'sessions' },
             path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :entries do
    resources :reports
    member do
      put 'upvote'
      put 'unupvote'
      put 'downvote'
      put 'undownvote'
      put 'save_entry'
      put 'unsave_entry'
      put 'verify'
      put 'unverify'
    end
  end

  match 'help', to: 'messages#new', :via => 'get'
  resources :messages, only: [:create]

  root 'entries#index'
  match 'reports', to: 'flags#index', :via => 'get'
  match 'search', to: 'pages#search', :via => 'get'
  match 'trending', to: 'pages#trending', :via => 'get'
  match 'users', to: 'pages#users', :via => 'get'
  match 'verify', to: 'pages#verify', :via => 'get'
  match 'about', to: 'pages#about', :via => 'get'
  match 'privacy', to: 'pages#privacy', :via => 'get'
  match 'terms', to: 'pages#terms', :via => 'get'
  match 'guidelines', to: 'pages#guidelines', :via => 'get'
  match 'competition', to: 'pages#competition', :via => 'get'

  # Make sure profile routes are always last to allow mis-routing
  # See https://stackoverflow.com/questions/16796244/rails-username-in-url
  get ':username', to: 'profiles#show', as: :profile
  get ':username/votes', to: 'profiles#votes', as: :votes
  get ':username/saved', to: 'profiles#saved', as: :saved
  get ':username/verified', to: 'profiles#verified', as: :verified
end

app/models/entry.rb
class Entry < ApplicationRecord
  # https://github.com/norman/friendly_id
  extend FriendlyId
  friendly_id :link
  acts_as_votable cacheable_strategy: :update_columns
  paginates_per 15
  has_paper_trail

  # https://guides.rubyonrails.org/association_basics.html
  # options-for-belongs-to-counter-cache
  belongs_to :user, counter_cache: true
  has_many :reports, dependent: :destroy
  accepts_nested_attributes_for :reports

  validates_presence_of :user_id

  validates :translation, presence: { message: "Translation type is missing!"}

  validates :from,
            presence: { message: "can't be empty"},
            format: { with: /\A[a-zA-Z,.?!'‘`’\-\s]*\z/, message: "text contains invalid character(s)"}

  validates :to,
            presence: { message: "can't be empty"},
            format: { with: /\A[a-zA-Z,.?!'‘`’\-\s]*\z/, message: "text contains invalid character(s)"}

  # Only validate using scopes on update. This is due to some filtering requirements for the model Entry
  validates :from, uniqueness: { scope: [ :to, :language ], message: 'translation already exists.' }#, on: :update
  validates :to, uniqueness: { scope: [ :from, :language ], message: 'translation already exists.' }#, on: :update

  # Only validate using the specified method on create
  validate :entry_uniqueness, on: :create

  private

  def entry_uniqueness
    squish_entry

    if Entry.where('"language" = ? AND "from" = ? AND "to" = ?',
                   language, from.downcase, to.downcase).exists?
      errors.add(:base, 'Identical translation already exists.')

    elsif Entry.where('"language" = ? AND "to" = ? AND "from" = ?',
                      language, from.downcase, to.downcase).exists?
      errors.add(:base, 'Reverse identical translation already exists.')
    end
  end

  def squish_entry
    self.from = self.from.squish
    self.to = self.to.squish
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, except: [:new, :create, :index]
  before_action :authenticate_user!, except: [:new, :create, :index, :show]
  before_action :set_paper_trail_whodunnit, only: [:create, :destroy, :update]
  before_action :kalipi_sign_in, only: :create
  after_action :kalipi_sign_out, only: :create
  before_action :require_username
  invisible_captcha only: [:create]

  def new
    custom_meta_tags('Create translation',
                     'Create a new, unique and interesting translation from English to Oshiwambo
                                and be part of Elaka.',
                     %w[create new post translate learn oshiwambo])

    @entry = Entry.new
    @kalipi = User.find_by(username: "kalipi")
  end

  def create
    @entry = current_user.entries.build(entry_params)

    if @entry.valid?
      @entry.save
      flash[:notice] = "Your translation was posted."

      # for anonymous id routing, update :link based on id
      @entry.update_column(:link, ((@entry.id**3).to_s(36)))

      # temporary for the competition
      # if @entry.created_at >= DateTime.parse("2021-04-27 22:00:00")
      #  count = current_user.competition
      # unless count
      #   count = 0
      # end
      # count += 1
      # current_user.update_column(:competition, count)
      # end

      redirect_to new_entry_path
    else
      flash.now[:error] = @entry.errors.full_messages[0]
      render :new
    end
  end

  def index
    custom_meta_tags('Translations',
                     'Learn Oshiwambo is where numerous community members shape the future of Oshiwambo
                                language, together. Contribute to the open source community, manage your translation
                                entries, educate others',
                     %w[learn oshiwambo elaka Translations translate english oshindonga oshikwanyama])

    @entries = Entry.order(created_at: :desc).page params[:page]
  end

  def show
    from_value = @entry.from.split
    to_value = @entry.to.split

    custom_meta_tags("@#{ @entry.user.username } on Elaka:
                            #{ @entry.from.chars.first(10).join } translates to
                            #{ @entry.to.chars.first(10).join }",
                     "#{ @entry.from } translates to #{ @entry.to }",
                     from_value + to_value + %w[Translation translate learn oshiwambo english oshindonga oshikwanyama])
    @reports = @entry.reports
  end

  def edit
    from_value = @entry.from.split
    to_value = @entry.to.split

    custom_meta_tags("Edit translation: #{ @entry.from.chars.first(10).join } ->
                            #{ @entry.to.chars.first(10).join }",
                     "#{ @entry.from } -> #{ @entry.to }",
                     from_value + to_value + %w[edit learn oshiwambo])
  end

  def update
    if @entry.valid?
      @entry.update(entry_params)
      flash[:notice] = "Translation was updated."
      redirect_to(entry_path(@entry))
    else
      flash.now[:error] = @entry.errors.full_messages[0]
      render :edit
    end
  end

  def destroy
    @entry.destroy
  end

  def upvote
    @entry.liked_by current_user, :vote_scope => 'vote'
  end

  def unupvote
    @entry.unliked_by current_user, :vote_scope => 'vote'
  end

  def downvote
    @entry.disliked_by current_user, :vote_scope => 'vote'
  end

  def undownvote
    @entry.undisliked_by current_user, :vote_scope => 'vote'
  end

  def save_entry
    @entry.liked_by current_user, :vote_scope => 'saved'
  end

  def unsave_entry
    @entry.unliked_by current_user, :vote_scope => 'saved'
  end

  def verify
    @entry.liked_by current_user, :vote_scope => 'verify'
  end

  def unverify
    @entry.unliked_by current_user, :vote_scope => 'verify'
  end

  private

  def set_entry
    @entry = Entry.friendly.find(params[:id])
  end

  # parameters include user_id
  def entry_params
    params.require(:entry).permit(:translation, :from, :to, :language, user: current_user)
  end

  # manage default user kalipi when no one else is signed in
  def kalipi_sign_in
    unless signed_in?
      sign_in(User.find_by(username: 'kalipi'))
    end
  end

  def kalipi_sign_out
    if current_user.username == 'kalipi'
      sign_out(current_user)
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper

  # For likes and dislikes counts. Only display number for > 0
  def trim_zero(number)
    return '' if number <= 0
    number
  end

  #number_to_human(number, :format => '%n%u',
  #                :precision => 2,
  #                :units => { :thousand => 'K', :million => 'M', :billion => 'B' })
end

app/views/entries/_decide_vote.html.erb
<!--suppress ALL -->
<% unless user_signed_in? %>
  <%= render 'entries/vote_not_signed_in', entry: @entry %>
<% else %>

  <% if current_user.voted_up_on? @entry, :vote_scope => 'vote' %>
    <%= render 'entries/unupvote', entry: @entry %>
    <%= render 'entries/downvote', entry: @entry %>
  <% elsif current_user.voted_down_on? @entry, :vote_scope => 'vote' %>
    <%= render 'entries/upvote', entry: @entry %>
    <%= render 'entries/undownvote', entry: @entry %>
  <% else %>
    <%= render 'entries/upvote', entry: @entry %>
    <%= render 'entries/downvote', entry: @entry %>
  <% end %>
<% end %>

app/views/entries/_index.html.erb
<% mod_count = 0 %>
<% sign_count = 0 %>
<% other_count = 0 %>
<% comp_count = 2 %>
<% @entries.each do | entry | %>

  <% unless user_signed_in? %>
    <% if  sign_count == 0 %>
      <div class="text-gray small text-center" style="padding-bottom: 1em;">
        <%= link_to "Create", new_registration_path(resource_name), class: "text-yellow" %> account
        or
        <%= link_to "Log In", new_session_path(resource_name), class: "text-yellow" %>
        to contribute now.
      </div>
    <% end %>
    <% sign_count = sign_count + 1 %>
  <% end %>

  <% if comp_count == 0 %>
    <div class="text-gray small text-center" style="padding-bottom: 1em;">
      <%= link_to "Who's winning CASH?", competition_path, class: "text-yellow" %>
    </div>
  <% end %>
  <% comp_count = comp_count + 1 %>

  <%= render 'entries/entry', entry: entry %>

  <% if (user_signed_in? and not current_user.moderator?) or not user_signed_in? %>
    <% if mod_count % 20 == 0 %>
      <div class="text-secondary small text-center" style="padding-top: 1em; padding-bottom: 1em;">
        Become a <%= link_to "moderator", help_path, class: "text-yellow" %> now! |
        Check <%= link_to "this", about_path, class: "text-yellow" %> 🚀🌕
      </div>
    <% else %>
      <br>
    <% end %>
    <% mod_count = mod_count + 1 %>
  <% elsif other_count % 20 == 0 %>
    <div class="text-secondary small text-center" style="padding-top: 1em; padding-bottom: 1em;">
      Check <%= link_to "this", about_path, class: "text-yellow" %> 🚀🌕
    </div>
    <% other_count = other_count + 1 %>
  <% else %>
    <br>
  <% end %>

<% end %>

app/views/entries/_save.html.erb
<!--suppress ALL -->
<% if defined? entry %>
  <% @entry = entry %>
<% end %>

<span id="save-container-<%= @entry.id %>">
  <% unless user_signed_in? %>
    <%=  render 'entries/save_entry', entry: @entry %>
  <% else %>
    <% if current_user.voted_up_on? @entry, :vote_scope => 'saved' %>
      <%= render 'entries/unsave_entry', entry: @entry %>
    <% else current_user.voted_up_on? @entry, :vote_scope => 'saved' %>
      <%=  render 'entries/save_entry', entry: @entry %>
    <% end %>
  <% end %>
</span>

<script>
    // if user not signed in, redirect to login page
    function goToSignIn() {
        if (<%= not user_signed_in? %>) {
            window.location.pathname = "<%= new_user_session_path %>"
        }
    }
</script>

app/views/entries/_unsave_entry.html.erb
<!--suppress ALL -->
<span id="unsave-form-<%= @entry.id %>">
  <%= link_to unsave_entry_entry_path(@entry), class: "btn-sm m-0 btn-outline-light text-decoration-none",
              remote: true, method: :put, style: "color: #ababab;" do %>
  <i class="bi bi-bookmark-plus-fill custom-blue" style="font-size: 1.2em;"></i>
<% end %>
</span>

app/views/entries/_unupvote.html.erb
<!--suppress ALL -->
<%= button_to unupvote_entry_path(entry), remote: true, method: :put, class: "btn btn-light like" do %>
  <i class="bi bi-hand-thumbs-up-fill custom-blue" id="unupvote-icon-<%= entry.id  %>"></i>
  <small class="custom-blue" id="unupcount-<%= entry.id %>" >
    <%= trim_zero(entry.get_likes(:vote_scope => 'vote').size) %>
  </small>
<% end %>

app/views/entries/_vote_not_signed_in.html.erb
<!--suppress ALL -->
<%= button_to upvote_entry_path(entry), remote: true, method: :put,
              class: "btn btn-light like", onclick: "goToSignIn();" do %>
  <i class="bi bi-hand-thumbs-up" style="color: #ababab;" ></i>
  <small style="color: #ababab;">
    <%= trim_zero(entry.get_likes(:vote_scope => 'vote').size) %>
  </small>
<% end %>

<%= button_to downvote_entry_path(entry), remote: true, method: :put,
              class: "btn btn-light dislike", onclick: "goToSignIn();" do %>
  <i class="bi bi-hand-thumbs-down" style="color: #ababab;" ></i>
  <small style="color: #ababab;">
    <%= trim_zero(entry.get_dislikes(:vote_scope => 'vote').size) %>
  </small>
<% end %>

<script>
    // if user not signed in, redirect to login page
    // if user not signed in, redirect to login page
    function goToSignIn() {
        if (<%= not user_signed_in? %>) {
            window.location.pathname = "<%= new_user_session_path %>"
        }
    }
</script>

app/views/entries/downvote.js.erb
$("#vote-container-<%= @entry.id %>").html("<%= escape_javascript(render partial: 'entries/decide_vote') %>")

app/views/entries/index.html.erb
<!--suppress CheckTagEmptyBody -->
<br>
<div id="entries-wrap">
  <%= render 'entries/index' %>
</div>
<div id="load-more-entries" class="text-center">
  <%= link_to_next_page @entries, 'load more', remote: true,
                        class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>
</div>
<br>
<br>

app/views/entries/show.html.erb
<!--suppress CheckTagEmptyBody -->

<br>

<%= render 'entries/entry', entry: @entry %>

<br>

<% if @entry.reports_count > 0 %>
  <p class="text-secondary font-weight-bold">
    <%= pluralize(@entry.reports_count, 'report') %>
  </p>
  <hr class="custom-horizontal">

  <% @reports.each do |report| %>
    <%= render 'flags/content', report: report %>
  <% end %>

<% end %>
<br>
<br>

app/views/entries/undownvote.js.erb
$("#vote-container-<%= @entry.id %>").html("<%= escape_javascript(render partial: 'entries/decide_vote') %>")

app/views/entries/unsave_entry.js.erb
$("#save-container-<%= @entry.id %>").html("<%= escape_javascript(render partial: 'entries/save_entry') %>")

app/views/entries/unupvote.js.erb
$("#vote-container-<%= @entry.id %>").html("<%= escape_javascript(render partial: 'entries/decide_vote') %>")

app/views/entries/upvote.js.erb
$("#vote-container-<%= @entry.id %>").html("<%= escape_javascript(render partial: 'entries/decide_vote') %>")