config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Check this
  # http://blog.railsupgrade.com/2014/05/how-to-override-devise-default-routes.html

  devise_for :users,
             :controllers => { :registrations => 'registrations', :confirmations => 'confirmations',
                               :sessions => 'sessions' },
             path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :entries do
    resources :reports
    member do
      put 'upvote'
      put 'unupvote'
      put 'downvote'
      put 'undownvote'
      put 'save_entry'
      put 'unsave_entry'
      put 'verify'
      put 'unverify'
    end
  end

  match 'help', to: 'messages#new', :via => 'get'
  resources :messages, only: [:create]

  root 'entries#index'
  match 'reports', to: 'flags#index', :via => 'get'
  match 'search', to: 'pages#search', :via => 'get'
  match 'trending', to: 'pages#trending', :via => 'get'
  match 'users', to: 'pages#users', :via => 'get'
  match 'verify', to: 'pages#verify', :via => 'get'
  match 'about', to: 'pages#about', :via => 'get'
  match 'privacy', to: 'pages#privacy', :via => 'get'
  match 'terms', to: 'pages#terms', :via => 'get'
  match 'guidelines', to: 'pages#guidelines', :via => 'get'
  match 'competition', to: 'pages#competition', :via => 'get'

  # Make sure profile routes are always last to allow mis-routing
  # See https://stackoverflow.com/questions/16796244/rails-username-in-url
  get ':username', to: 'profiles#show', as: :profile
  get ':username/votes', to: 'profiles#votes', as: :votes
  get ':username/saved', to: 'profiles#saved', as: :saved
  get ':username/verified', to: 'profiles#verified', as: :verified
end

app/views/shared/_dummy.html.erb
<!-- This file is full of crappy, dummy & experimental snippets -->
<!--suppress ALL -->
<%= render 'pages/search/hots' %>

<button class="input-group-text toggle-password-btn bg-white" onclick="removeHot()" type="submit">
  <i class="bi bi-search" aria-hidden="true"></i>
</button>

<%= link_to new_review_path(entry),
            class: "btn-sm m-0 btn-outline-secondary text-decoration-none text-center justify-content-center",
            style: "background-color: #ababab; color: white; float: right; height: 2em; padding-top: 2px;" do %>
  <small>
    <i class="bi bi-patch-question-fill" data-bs-toggle="tooltip"
       data-bs-placement="top" title="Verify Translation">  Verify</i>
  </small>
<% end %>

<input class="form-check-input" type="checkbox" id="edit-verify-<%= entry.id %>"
       style="width: 5em; height: 1.4em; margin-top: 0;"
       onclick="submitEditReview(<%= entry.id%>)" <% checked %> >

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-7 my-auto">
      <button class="btn btn-light btn-block dropdown-toggle text-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#editYourDetails" aria-expanded="false" aria-controls="editYourDetails">
        Edit your details
      </button>
      <br>
      <div class="collapse" id="editYourDetails">
        <div class="card-group mb-0">
          <div class="card p-4">
            <div class="card-body">
              <div class="d-flex flex-column">
                <br>
                <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
                  <%= form_group_tag(resource.errors[:username]) do %>
                    <div class="field">
                      <%= f.text_field :username, class: 'form-control', placeholder: 'username' %>
                      <% resource.errors.full_messages_for(:username).each do |message| %>
                        <small class="help-block text-danger"><%= message %></small>
                      <% end %>
                    </div>
                  <% end %>

                  <%= form_group_tag(resource.errors[:email]) do %>
                    <div class="field">
                      <%= f.text_field :email, class: 'form-control', placeholder: 'email', autocomplete: "email" %>
                      <% resource.errors.full_messages_for(:email).each do |message| %>
                        <small class="help-block text-danger"><%= message %></small>
                      <% end %>
                    </div>
                  <% end %>

                  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
                    <div>
                      Currently waiting confirmation for: <%= resource.unconfirmed_email %>
                    </div>
                  <% end %>

                  <%= form_group_tag(resource.errors[:current_password]) do %>
                    <div class="field">
                      <%= f.password_field :current_password, autocomplete: "new-password",
                                           class: 'form-control', placeholder: 'Enter current password' %>
                      <% resource.errors.full_messages_for(:current_password).each do |message| %>
                        <small class="help-block text-danger"><%= message %></small>
                        <br>
                      <% end %>
                      <small class="help-block text-secondary">
                        We need your current password to confirm your changes
                      </small>
                    </div>
                  <% end %>

                  <button class="btn btn-outline-light btn-block dropdown-toggle text-secondary" type="button" data-bs-toggle="collapse" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="newPassword confirmNewPassword">
                    Change current password
                  </button>

                  <div class="collapse multi-collapse" id="newPassword">
                    <%= form_group_tag(resource.errors[:password]) do %>
                      <div class="field">
                        <small class="text-secondary">
                          <% if @minimum_password_length %>
                            <%= @minimum_password_length %> characters minimum.
                          <% end %><br/>
                        </small>
                        <%= f.password_field :password, autocomplete: "new-password",
                                             class: 'form-control', placeholder: 'New password' %>
                        <% resource.errors.full_messages_for(:password).each do |message| %>
                          <small class="help-block text-danger"><%= message %></small>
                        <% end %>
                      </div>
                    <% end %>
                  </div>

                  <div class="collapse multi-collapse" id="confirmNewPassword">
                    <%= form_group_tag(resource.errors[:password_confirmation]) do %>
                      <div class="field">
                        <small class="text-secondary">
                          Leave blank if you don't want to change it
                        </small>
                        <%= f.password_field :password_confirmation, autocomplete: "new-password",
                                             class: 'form-control', placeholder: 'confirm new password' %>
                        <% resource.errors.full_messages_for(:password_confirmation).each do |message| %>
                          <small class="help-block text-danger"><%= message %></small>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                  <br>
                  <div class="form-group">
                    <div class="actions">
                      <%= f.submit "Update Details", class: "btn btn-primary btn-block pull-right" %>
                    </div>
                  </div>
                <% end %>
                <hr>

                <div class="col-md-6 text-center mx-auto">
                  <h6>
                    Unhappy?
                  </h6>
                </div>

                <%= button_to "Delete Account", registration_path(resource_name),
                              class: "btn btn-danger btn-block",
                              data: { confirm: "Are you sure?" },
                              method: :delete %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    function updateUpvote(id) {
        let upvote = document.getElementById('upvote-' + id)
        let upcount = document.getElementById('upcount-' + id)
        let downvote = document.getElementById('downvote-' + id)
        let downcount = document.getElementById('downcount-' + id)

        if (<%= user_signed_in? %> && <%= current_user.voted_up_on? entry %>) {
            upvote.className = "bi bi-hand-thumbs-up";
            upvote.style.color = "#ababab";
            upcount.innerHTML = <%= votes_in_words(entry.get_upvotes.size) %> - 1;
        }

    else if (<%= user_signed_in? %> && <%= current_user.voted_down_on? entry %>) {
            upvote.className = "bi bi-hand-thumbs-up-fill";
            upvote.style.color = "#007bff";
            upcount.innerHTML = <%= votes_in_words(entry.get_upvotes.size) %> + 1;

            downvote.className = "bi bi-hand-thumbs-down";
            downvote.style.color = "#ababab";
            downcount.innerHTML = <%= votes_in_words(entry.get_downvotes.size) %> - 1;
            console.log('here')
        }

    else {
            upvote.className = "bi bi-hand-thumbs-up-fill";
            upvote.style.color = "#007bff";
            upcount.innerHTML = <%= votes_in_words(entry.get_upvotes.size) %> + 1;
        }
    }

    function updateDownvote(id) {
        let upvote = document.getElementById('upvote-' + id);
        let upcount = document.getElementById('upcount-' + id);
        let downvote = document.getElementById('downvote-' + id);
        let downcount = document.getElementById('downcount-' + id);

        if (<%= user_signed_in? %> && <%= current_user.voted_down_on? entry %>) {
            downvote.className = "bi bi-hand-thumbs-down";
            downvote.style.color = "#ababab";
            downcount.innerHTML = <%= votes_in_words(entry.get_downvotes.size) %> - 1;
        }

    else if (<%= user_signed_in? %> && <%= current_user.voted_up_on? entry %>) {
            upvote.className = "bi bi-hand-thumbs-up";
            upvote.style.color = "#ababab";
            upcount.innerHTML = <%= votes_in_words(entry.get_upvotes.size) %> - 1;

            downvote.className = "bi bi-hand-thumbs-down-fill";
            downvote.style.color = "#007bff";
            downcount.innerHTML = <%= votes_in_words(entry.get_downvotes.size) %> + 1;
        }

    else {
            downvote.className = "bi bi-hand-thumbs-down-fill";
            downvote.style.color = "#007bff";
            downcount.innerHTML = <%= votes_in_words(entry.get_downvotes.size) %> + 1;
        }
    }
</script>

<!--suppress ALL -->
<% if user_signed_in? and current_user.voted_up_on? entry %>
  <%= button_to unupvote_entry_path(entry), remote: true, method: :put,
                class: "btn btn-light like",
                id: "unupvote-button-#{ entry.id }" do %>
    <i class="bi bi-hand-thumbs-up-fill" style="color: #007bff;" id="unupvote-icon-<%= entry.id  %>"></i>
    <small id="upcount-<%= entry.id %>" style="color: #ababab;" >
      <%= votes_in_words(entry.get_likes.size) %>
    </small>
  <% end %>

<% elsif user_signed_in? and not current_user.voted_up_on? entry %>
  <%= button_to upvote_entry_path(entry), remote: true, method: :put,
                class: "btn btn-light like",
                id: "upvote-button-#{ entry.id }" do %>
    <i class="bi bi-hand-thumbs-up" style="color: #ababab;" id="upvote-icon-<%= entry.id  %>"></i>
    <small id="upcount-<%= entry.id %>" style="color: #ababab;">
      <%= votes_in_words(entry.get_likes.size) %>
    </small>
  <% end %>
<% end %>

<% if user_signed_in? and current_user.voted_down_on? entry %>
  <%= button_to undownvote_entry_path(entry), remote: true, method: :put,
                class: "btn btn-light dislike",
                id: "undownvote-button-#{ entry.id }" do %>
    <i class="bi bi-hand-thumbs-down-fill" style="color: #007bff;" id="undownvote-icon-<%= entry.id  %>"></i>
    <small id="downcount-<%= entry.id %>" style="color: #ababab;" >
      <%= votes_in_words(entry.get_dislikes.size) %>
    </small>
  <% end %>

<% elsif user_signed_in? and not current_user.voted_down_on? entry %>
  <%= button_to downvote_entry_path(entry), remote: true, method: :put,
                class: "btn btn-light dislike",
                id: "downvote-button-#{ entry.id }" do %>
    <i class="bi bi-hand-thumbs-down" style="color: #ababab;" id="downvote-icon-<%= entry.id  %>"></i>
    <small id="downcount-<%= entry.id %>" style="color: #ababab;">
      <%= votes_in_words(entry.get_dislikes.size) %>
    </small>
  <% end %>
<% end %>

<!-- Links to buttons -->
<%= link_to search_path, class: "btn-sm m-0 btn-outline-light text-decoration-none", style: "color: #ababab;" do %>
  <i class="bi bi-bookmark-plus" data-bs-toggle="tooltip" data-bs-placement="top" title="Save to bookmarks"></i>
<% end %>

<%= link_to search_path, class: "btn-sm m-0 btn-outline-light text-decoration-none ", style: "color: #ababab;" do %>
  <i class="bi bi-flag" data-bs-toggle="tooltip" data-bs-placement="top" title="Report translation"></i>
<% end %>

<%= link_to search_path, class: "btn-sm m-0 btn-outline-light text-decoration-none ", style: "color: #ababab;" do %>
  <i class="bi bi-share" data-bs-toggle="tooltip" data-bs-placement="top" title="Copy link"></i>
<% end %>


<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<!--suppress ALL -->
<br>
<div class="sticky-top">
  <div class="card p-3 border-0 shadow-sm">

    <%= link_to image_tag('logo512Black.png', alt: 'logo'), root_path,
                class: 'logo btn menu-btn btn-outline-light text-left text-secondary'%>

    <%= link_to root_path, class: "btn menu-btn btn-outline-light text-left text-secondary" do %>
      <i class="bi bi-house-fill icon-btn" style="font-size: 1rem;"></i>
      <strong class="menu-btn-text">Home</strong>
    <% end %>

    <%= link_to new_entry_path, class: "btn menu-btn btn-outline-primary text-left" do %>
      <i class="bi bi-plus-circle-fill icon-btn" style="font-size: 1rem;"></i>
      <strong class="menu-btn-text" style="padding-right: 5px">Post</strong>
    <% end %>

    <%= link_to search_path, class: "btn menu-btn btn-outline-light text-left text-secondary" do %>
      <i class="bi bi-search icon-btn" style="font-size: 1rem;"></i>
      <strong class="menu-btn-text">Search</strong>
    <% end %>

    <%= link_to trending_path, class: "btn menu-btn btn-outline-light text-left text-secondary" do %>
      <i class="bi bi-sunrise-fill icon-btn" style="font-size: 1rem;"></i>
      <strong class="menu-btn-text">Trending</strong>
    <% end %>

    <%= link_to reports_path, class: "btn menu-btn btn-outline-light text-left text-secondary" do %>
      <i class="bi bi-flag-fill icon-btn" style="font-size: 1rem;"></i>
      <strong class="menu-btn-text">Reports</strong>
    <% end %>

    <% if user_signed_in? and current_user.moderator? %>
      <%= link_to verify_path, class: "btn menu-btn btn-outline-light text-left text-secondary" do %>
        <i class="bi bi-patch-check-fill icon-btn" style="font-size: 1rem;"></i>
        <strong class="menu-btn-text">Verify</strong>
      <% end %>
    <% end %>

    <%= link_to users_path, class: "btn menu-btn btn-outline-light text-left text-secondary" do %>
      <i class="bi bi-people-fill icon-btn" style="font-size: 1rem;"></i>
      <strong class="menu-btn-text" style="padding-right: 5px">Users</strong>
    <% end %>

    <%= link_to about_path, class: "btn menu-btn btn-outline-light text-left text-secondary" do %>
      <i class="bi bi-info-circle-fill icon-btn" style="font-size: 1rem;"></i>
      <strong class="menu-btn-text">About?</strong>
    <% end %>

    <%= link_to help_path, class: "btn menu-btn btn-outline-light text-left text-secondary" do %>
      <i class="bi bi-question-circle-fill icon-btn" style="font-size: 1rem;"></i>
      <strong class="menu-btn-text">Help?</strong>
    <% end %>

    <% if user_signed_in? and (current_user.supervisor? or current_user.superuser?) %>
      <%= link_to rails_admin_path, target: :_blank,
                  class: "btn menu-btn btn-outline-light text-left text-secondary" do %>
        <i class="bi bi-grid-fill icon-btn" style="font-size: 1rem;"></i>
        <strong class="menu-btn-text">Admin</strong>
      <% end %>
    <% end %>

    <hr class="custom-horizontal">

    <ul class="navbar-nav mb-2 mb-lg-0">

      <% if user_signed_in? and current_user.username? %>

        <%= link_to profile_path(current_user), class: "btn menu-btn btn-outline-light text-left text-secondary" do %>
          <strong class="menu-btn-text">
            <%= "@" + current_user.username %>
            <%= is_moderator(current_user) %>
          </strong>
        <% end %>

        <button class="btn menu-btn btn-block btn-outline-light text-left text-secondary dropdown-toggle"
                type="button" data-bs-toggle="collapse" data-bs-target=".menu-collapse"
                aria-expanded="false" aria-controls="dashboard logout">
          <strong class="menu-btn-text">Profile</strong>
        </button>

        <div class="collapse menu-collapse" style="margin-top: 0.4em;" id="dashboard">
          <%= link_to edit_user_registration_path, class: "btn menu-btn btn-block btn-outline-light text-left text-secondary" do %>
            <strong class="menu-btn-text">Edit Details</strong>
          <% end %>
        </div>

        <div class="collapse menu-collapse" id="logout">
          <%= link_to destroy_user_session_path, class: "btn menu-btn btn-block btn-outline-light text-left text-secondary" do %>
            <strong class="menu-btn-text">Log out</strong>
          <% end %>
        </div>

      <% else # user not signed it %>
        <!-- Button to trigger sign in modal -->
        <%= link_to 'Sign In', new_user_session_path,  class: "btn btn-sm btn-primary navbar-btn font-weight-bold"  %>
      <% end # if user is signed it %>

    </ul>

  </div>
</div>

app/views/shared/_mobile_menu.html.erb
<!--suppress CheckTagEmptyBody -->
<div class="fixed-bottom mobile-menu">
  <div class="row">
    <div class="col p-0">
      <nav>
        <div class="nav p-0 nav-tabs nav-fill">
          <%= link_to root_path, class: "remove-webkit btn nav-link text-secondary mobile-menu-btn",
                      type: "button", id: "menu-one", onclick: "changeActiveOne()" do %>
            <i class="bi bi-house-door-fill text-yellow"></i>
          <% end %>

          <%= link_to trending_path, class: "remove-webkit btn nav-link text-secondary mobile-menu-btn",
                      type: "button", id: "menu-two", onclick: "changeActiveTwo()" do %>
            <i class="bi bi-sunrise-fill text-yellow"></i>
          <% end %>

          <%= link_to new_entry_path, class: "remove-webkit btn nav-link text-secondary mobile-menu-btn",
                      type: "button", id: "menu-three", onclick: "changeActiveThree()" do %>
            <i class="bi bi-plus-circle-fill text-yellow"></i>
          <% end %>

          <%= link_to search_path, class: "remove-webkit btn nav-link text-secondary mobile-menu-btn",
                      type: "button", id: "menu-four", onclick: "changeActiveFour()" do %>
            <i class="bi bi-search text-yellow"></i>
          <% end %>

          <button class="mobile-menu-btn btn" type="button" data-bs-toggle="collapse" data-bs-target="#toggleMobileNav"
                  aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"
                  id="menu-five" onclick="changeActiveFive()">
            <i class="bi bi-layers-fill text-yellow"></i>
          </button>

          <div class="collapse navbar-collapse" id="toggleMobileNav">
            <div class="navbar-nav" style="border-top: 1px solid #6c757d;">
              <% if user_signed_in? and current_user.username? %>
                <%= link_to profile_path(current_user), type: "button",
                            class: "remove-webkit btn dropdown-mobile-btn text-right text-secondary" do %>
                  <span style="font-size: 1.1em;">
                    <%= "@" + current_user.username %>
                    <%= is_moderator(current_user) %>
                  </span>
                <% end %>

                <% if current_user.supervisor? or current_user.superuser? %>
                  <%= link_to rails_admin_path, type: "button", target: :_blank,
                              class: "remove-webkit btn dropdown-mobile-btn text-right text-secondary" do %>
                    <span>Admin Dashboard</span>
                  <% end %>
                <% end %>
              <% end %>

              <% if user_signed_in? and current_user.moderator? %>
                <%= link_to verify_path, type: "button",
                            class: "remove-webkit btn dropdown-mobile-btn text-right text-secondary" do %>
                  <span>Verify Translations</span>
                <% end %>
              <% end %>

              <%= link_to reports_path, type: "button",
                          class: "remove-webkit btn dropdown-mobile-btn text-right text-secondary" do %>
                <span>Reported Translations</span>
              <% end %>

              <%= link_to users_path, type: "button",
                          class: "remove-webkit btn dropdown-mobile-btn text-right text-secondary" do %>
                <span>Search Users</span>
              <% end %>

              <%= link_to help_path, type: "button",
                          class: "remove-webkit btn dropdown-mobile-btn text-right text-secondary" do %>
                <span>Need help?</span>
              <% end %>

              <%= link_to about_path, type: "button",
                          class: "remove-webkit btn dropdown-mobile-btn text-right text-secondary" do %>
                <span>About</span>
              <% end %>

              <% if user_signed_in? %>
                <%= link_to edit_user_registration_path, type: "button",
                            class: "remove-webkit btn dropdown-mobile-btn text-right text-secondary" do %>
                  <span>Edit Profile</span>
                <% end %>

                <%= link_to destroy_user_session_path, type: "button",
                            class: "remove-webkit btn dropdown-mobile-btn text-right text-secondary" do %>
                  <span>Log Out</span>
                <% end %>

              <% else %>

                <%= link_to new_user_session_path, type: "button", style: "background-color: #ffa200;",
                            class: "remove-webkit btn font-weight-bold text-right text-secondary" do %>
                  <span class="text-light">Sign In</span>
                <% end %>
              <% end %>
            </div>
          </div>

      </div>
      </nav>
    </div>
  </div>
</div>

<script>
  // Simulate bottom mobile menu
  function changeActiveOne() {
      let activeClass = "remove-webkit btn nav-link active text-secondary mobile-menu-btn"
      let nonActiveClass = "remove-webkit btn nav-link text-secondary mobile-menu-btn"
      $('#menu-one').removeClass().addClass(activeClass)
      $('#menu-two').removeClass().addClass(nonActiveClass)
      $('#menu-three').removeClass().addClass(nonActiveClass)
      $('#menu-four').removeClass().addClass(nonActiveClass)
      $('#menu-five').removeClass().addClass(nonActiveClass)
      localStorage.setItem('menu', 'one')
  }

  function changeActiveTwo() {
      let activeClass = "remove-webkit btn nav-link active text-secondary mobile-menu-btn"
      let nonActiveClass = "remove-webkit btn nav-link text-secondary mobile-menu-btn"
      $('#menu-one').removeClass().addClass(nonActiveClass)
      $('#menu-two').removeClass().addClass(activeClass)
      $('#menu-three').removeClass().addClass(nonActiveClass)
      $('#menu-four').removeClass().addClass(nonActiveClass)
      $('#menu-five').removeClass().addClass(nonActiveClass)
      localStorage.setItem('menu', 'two')
  }

  function changeActiveThree() {
      let activeClass = "remove-webkit btn nav-link active text-secondary mobile-menu-btn"
      let nonActiveClass = "remove-webkit btn nav-link text-secondary mobile-menu-btn"
      $('#menu-one').removeClass().addClass(nonActiveClass)
      $('#menu-two').removeClass().addClass(nonActiveClass)
      $('#menu-three').removeClass().addClass(activeClass)
      $('#menu-four').removeClass().addClass(nonActiveClass)
      $('#menu-five').removeClass().addClass(nonActiveClass)
      localStorage.setItem('menu', 'three')
  }

  function changeActiveFour() {
      let activeClass = "remove-webkit btn nav-link active text-secondary mobile-menu-btn"
      let nonActiveClass = "remove-webkit btn nav-link text-secondary mobile-menu-btn"
      $('#menu-one').removeClass().addClass(nonActiveClass)
      $('#menu-two').removeClass().addClass(nonActiveClass)
      $('#menu-three').removeClass().addClass(nonActiveClass)
      $('#menu-four').removeClass().addClass(activeClass)
      $('#menu-five').removeClass().addClass(nonActiveClass)
      localStorage.setItem('menu', 'four')
  }

  function changeActiveFive() {
      let activeClass = "remove-webkit btn nav-link active text-secondary mobile-menu-btn"
      let nonActiveClass = "remove-webkit btn nav-link text-secondary mobile-menu-btn"
      $('#menu-one').removeClass().addClass(nonActiveClass)
      $('#menu-two').removeClass().addClass(nonActiveClass)
      $('#menu-three').removeClass().addClass(nonActiveClass)
      $('#menu-four').removeClass().addClass(nonActiveClass)
      $('#menu-five').removeClass().addClass(activeClass)
      localStorage.setItem('menu', 'five')
  }

  var menuValue = localStorage.getItem('menu')
  if (menuValue === 'one') {
      changeActiveOne()
  }
  else if (menuValue === 'two') {
      changeActiveTwo()
  }
  else if (menuValue === 'three') {
      changeActiveThree()
  }
  else if (menuValue === 'four') {
      changeActiveFour()
  }
  else if (menuValue === 'five') {
      changeActiveFive()
  }
</script>

app/views/shared/_notices.html.erb
<!--suppress ALL -->
<% flash.each do |type, message| %>
  <% which = { "notice" => "success", "error" => "danger", "alert" => "yellow" } %>
  <div class="position-fixed top-0 start-50 translate-middle-x p-3" id="toast-flash" style="z-index: 5;">
    <div class="toast toast-flash align-items-center text-secondary border-0" style="background-color: #212529;"
         data-bs-delay="15000" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-body text-center">
        <span class="text-<%= which[type] %>"><%= message %></span>
        <button type="button" style="float: right; font-size: 0.7em;" class="btn-close btn-close-white" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
    </div>
  </div>
<% end %>

<script>
    if ($(window).width() < 992) {
        $('#toast-flash').removeClass().addClass("position-fixed bottom-0 translate-middle-x start-50 p-3");
        $('#toast-flash').css({'z-index' : '5', 'margin-bottom' : '3em'})
    }
    else {
        $('#toast-flash').removeClass().addClass("position-fixed top-0 end-0 p-3");
        $('#toast-flash').css({'z-index' : '5'})
    }

    $(document).ready(function () {
        $('.toast-flash').toast('show')
    })
</script>