config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Check this
  # http://blog.railsupgrade.com/2014/05/how-to-override-devise-default-routes.html

  devise_for :users,
             :controllers => { :registrations => 'registrations', :confirmations => 'confirmations',
                               :sessions => 'sessions' },
             path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :entries do
    resources :reports
    member do
      put 'upvote'
      put 'unupvote'
      put 'downvote'
      put 'undownvote'
      put 'save_entry'
      put 'unsave_entry'
      put 'verify'
      put 'unverify'
    end
  end

  match 'help', to: 'messages#new', :via => 'get'
  resources :messages, only: [:create]

  root 'entries#index'
  match 'reports', to: 'flags#index', :via => 'get'
  match 'search', to: 'pages#search', :via => 'get'
  match 'trending', to: 'pages#trending', :via => 'get'
  match 'users', to: 'pages#users', :via => 'get'
  match 'verify', to: 'pages#verify', :via => 'get'
  match 'about', to: 'pages#about', :via => 'get'
  match 'privacy', to: 'pages#privacy', :via => 'get'
  match 'terms', to: 'pages#terms', :via => 'get'
  match 'guidelines', to: 'pages#guidelines', :via => 'get'
  match 'competition', to: 'pages#competition', :via => 'get'

  # Make sure profile routes are always last to allow mis-routing
  # See https://stackoverflow.com/questions/16796244/rails-username-in-url
  get ':username', to: 'profiles#show', as: :profile
  get ':username/votes', to: 'profiles#votes', as: :votes
  get ':username/saved', to: 'profiles#saved', as: :saved
  get ':username/verified', to: 'profiles#verified', as: :verified
end

app/views/pages/_users.html.erb
<!--suppress ALL -->
<tr class="clickable-row" data-href="<%= profile_path(user) %>">
  <th class="table-row" scope="row">
    <%= "@" + user.username %>
    <%= is_moderator(user) %>
  </th>
  <td class="text-center table-row">
    <%= user.entries_count %>
  </td>
  <td class="text-right table-row">
    <%= user.created_at.strftime("%b %Y") %>
  </td>
</tr>

<script>
    $(document).ready(function () {
        $('[data-href]').click(function () {
            window.location = $(this).data("href");
        });
    });
</script>

app/views/pages/_users_more.html.erb
<% @users.each do | user | %>
  <% unless user.confirmed_at.blank? %>
    <%= render 'pages/users', user: user %>
  <% end %>
<% end %>

app/views/pages/_verify.html.erb
<% @entries.each do | entry | %>
  <%= render 'entries/entry', entry: entry %>
  <br>
<% end %>

app/views/pages/about.html.erb
<!--suppress ALL -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
      integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu"
      crossorigin="anonymous">
<p></p>

<p class="text-gray">
  Counting
  <span class="text-yellow">
    <% unless @count.blank? %>
      <%= @count %>
    <% end %>
  </span>
  translations 🚀🌕
</p>
<hr class="custom-horizontal">

<span>
  <strong class="text-yellow" style="font-size: 1.7em;">Why</strong>

  <span style="float: right; padding-top: 0.5em;">
    <a href="https://twitter.com/learnoshiwambo" style="font-size: 1.4em; color: transparent;" target="_blank">
      <i class="fab fa-twitter text-yellow"></i>
    </a>

    <a href="https://www.facebook.com/Learn-Oshiwambo-105380111449619" style="font-size: 1.4em; color: transparent;" target="_blank">
      <i class="fab fa-facebook text-yellow"></i>
    </a>

    <a href="https://www.instagram.com/learnoshiwambo/" style="font-size: 1.4em; color: transparent;" target="_blank">
      <i class="fab fa-instagram text-yellow"></i>
    </a>
  </span>
</span>
<hr class="custom-horizontal">

<p class="text-gray">Read our
  <%= link_to "Guidelines", guidelines_path, class: "text-yellow" %>
</p>

<p class="text-gray">Once upon a time I wanted to develop a translation intelligent-backed application for
  <span class="text-yellow">Namibian indigenous languages</span> particularly Oshiwambo, against English.
</p>

<p class="text-gray">One major obstacle was, and still is, lack of organised, open-source translation pairs.
  I know what you're thinking! Why not just source translations from an already available
  <span class="text-yellow" data-bs-toggle="tooltip" data-bs-placement="top" title="A dictionary or a word listing book.">
    embwiitya</span> like
  <a class="text-yellow text-decoration-none" target="_blank"
     href = "https://www.amazon.com/Oshindonga-English-Dictionary/dp/0868481823">this</a>
  or
  <a class="text-yellow text-decoration-none" target="_blank"
     href = "https://openlibrary.org/books/OL1268889M/Oshindonga_English_English_Oshindonga_embwiitya">this</a>?
  Not free!
</p>

<p class="text-gray">Hence why not create an online platform with trusted moderators where everyone can submit
  translations, and also learn?
</p>

<h2 class="text-yellow">Goals</h2>
<hr class="custom-horizontal">

<p class="text-gray">Contribute to Effective Communication • Aid in the
  Transmission of Knowledge • Preserve Cultural Heritage • Accelerate Education • More
</p>

<h2 class="text-yellow">Open Source</h2>
<hr class="custom-horizontal">

<p class="text-gray">All data submited on Elaka is free to reproduce and use in
  any desired (positive) manner. That's it!
</p>

<h2 class="text-yellow">Setup</h2>
<hr class="custom-horizontal">

<p class="text-gray">General Users: e.g.
  <% unless @general.blank? %>
    <%= link_to '@' + @general.username, profile_path(@general),
                class: 'text-decoration-none text-secondary' %>
  <% end %>
</p>

<p class="text-gray">
  Can create, vote, save and report translations. Created translations cannot
  be edited or deleted. In case you made an error, just create another translation.
</p>

<p class="text-gray">Moderators: e.g.
  <% unless @moderator.blank? %>
    <%= link_to '@' + @moderator.username, profile_path(@moderator),
                class: 'text-decoration-none text-secondary' %>
    <%= is_moderator(@moderator) %>
  <% end %>
</p>
<p class="text-gray">In addition to general user functionality, they can edit, delete and verify the correctness
  of translations. They can also review and remove reports/flags on translations.
</p>

<h2 class="text-yellow">Contribute?</h2>
<hr class="custom-horizontal">

<p class="text-gray">Are you a language educator, translation expert, intelligent software developer,
  computational linguist or perhaps an organization and would &#10084; to contribute?
</p>

<span>
  <a href="https://twitter.com/axelmukwena" style="font-size: 1.4em; color: transparent;" target="_blank">
    <i class="fab fa-twitter" style="color: #1b95e0; "></i>
  </a>

  <a href="https://www.linkedin.com/in/axelmukwena/" style="font-size: 1.4em; color: transparent;" target="_blank">
    <i class="fab fa-linkedin" style="color: #1b95e0;"></i>
  </a>

  <span class="text-gray" style="padding-left: 0.5em;">
    Developer, Axel Mukwena.
  </span>
</span>

<br>
<hr class="custom-horizontal">
<span class="text-gray">
  Need <%= link_to "help", help_path, class: "text-yellow" %>? |
  Reach <span class="text-yellow">osho@elaka.io</span>
</span>

<hr class="custom-horizontal">

<span class="text-gray">
  <%= link_to "Terms", terms_path, class: "text-yellow text-decoration-none" %>,
  <%= link_to "Privacy", privacy_path, class: "text-yellow text-decoration-none" %>
  <span class="text-gray" style="font-size: small">© 2021</span>
</span>
<br>
<br>
<br>
<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
    })
</script>

app/views/pages/competition.html.erb
<!--suppress ALL -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
      integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu"
      crossorigin="anonymous">


<strong class="text-yellow" style="font-size: 1.7em;">Competition has Ended</strong>
<div class="text-secondary m-0 p-0 small">
  Top 10 users with the highest number of entries
</div>
<hr class="custom-horizontal">

<table class="table table-custom table-hover text-gray">
  <thead>
  <tr style="font-weight: normal;">
    <th class="border-0" style="font-weight: normal;" scope="col">Username</th>
    <th class="border-0 text-center" style="font-weight: normal;" scope="col">Count</th>
    <th class="border-0 text-right" style="font-weight: normal;" scope="col">Joined</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do | user | %>
    <% unless user.confirmed_at.blank? or user.username.blank? or user.moderator? %>
      <%= render 'pages/competition', user: user %>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<strong class="text-yellow" style="font-size: 1.7em;">Competition Rules</strong>
<hr class="custom-horizontal">

<p class="text-gray">
  Win <span class="text-yellow">N$800</span> by submitting the highest number of correct translation entries.
</p>

<ul class="text-normal">
  <li>
    First winner: N$500
  </li>
  <li>
    Second Winner: N$300
  </li>
</ul>

<strong class="text-yellow" style="font-size: 1.7em;">Requirements</strong>
<hr class="custom-horizontal">

<ul class="text-normal">
  <li>
    3 words minimum for each translation entry
  </li>
  <li>
    No single words will qualify. Only sentences!
  </li>
</ul>

<div style="padding-left: 1em;">
  <p class="text-normal">
    <i class="bi bi-check-square-fill text-success" style=""></i>
    I like my dog -> Ondi hole ombwa yandje
  </p>

  <p class="text-normal">
    <i class="bi bi-check-square-fill text-success" style=""></i>
    Otandi li onyama -> I am eating meat
  </p>

  <p class="text-normal">
    <i class="bi bi-x-square-fill text-danger" style=""></i>
    Otandi li -> I am eating
  </p>

  <p class="text-normal">
    <i class="bi bi-x-square-fill text-danger" style=""></i>
    Onyama -> Meat
  </p>
</div>

<strong class="text-yellow" style="font-size: 1.7em;">Take Note</strong>
<hr class="custom-horizontal">

<ul class="text-normal">
  <li>
    You should be <%= link_to "logged in", new_session_path(resource_name), class: "text-yellow" %>
    . Only correct translation entries under your username will be considered
  </li>
  <li style="padding-top: 0.5em">
    Starting: <span class="text-yellow">00h00, 28th April 2021</span>
  </li>
  <li style="padding-top: 0.5em">
    Ending: <span class="text-yellow">18h00, 29th April 2021</span>
  </li>
  <li style="padding-top: 0.5em">
    Windhoek time.
  </li>
</ul>

<br>
<br>
<br>

app/views/pages/results.html.erb
<!--suppress ALL -->
<br>
<%= search_form_for @search, url: results_path do |f|%>
  <div class="form-group">
    <div class="field">
      <div class="input-group">
        <%= f.search_field :from_or_to_cont, class: "form-control session-form password-format-input",
                           placeholder: "konga / search" %>
        <button class="input-group-text toggle-password-btn bg-white" id="search-button" type="submit">
          <i class="bi bi-search" aria-hidden="true"></i>
        </button>
      </div>
    </div>
  </div>
<% end %>

<hr class="custom-horizontal">

<!-- Show search results -->
<p class="text-secondary font-weight-bold">Search Results</p>
<div id="results-wrap">
  <% @entries.each do | entry | %>
    <%= render 'entries/entry', entry: entry %>
    <br>
  <% end %>
</div>
<div id="load-more-results" class="text-center">
  <%= link_to_next_page @entries, 'load more', remote: true,
                        class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>
</div>
<br>

app/views/pages/search.html.erb
<!--suppress ALL -->
<br>
<%= search_form_for @search, url: search_path do |f|%>
  <div class="form-group">
    <div class="field">
      <div class="input-group">
        <%= f.search_field :from_or_to_cont, class: "form-control border-0 session-form password-format-input",
                           placeholder: "konga / search" %>
        <button class="input-group-text border-0 toggle-password-btn bg-white" id="search-button" type="submit">
          <i class="bi bi-search" aria-hidden="true"></i>
        </button>
      </div>
    </div>
  </div>
<% end %>

<!-- Show search results -->
<% if @entries.count > 10 %>
  <% filter = "More than 10 translations found" %>
<% else %>
  <% filter = pluralize(@entries.count, "translation") + " found" %>
<% end %>
<p class="text-secondary"><%= filter %></p>

<div id="search-wrap">
  <% @entries.each do | entry | %>
    <%= render 'entries/entry', entry: entry %>
    <br>
  <% end %>
</div>
<div id="search-load-more" class="text-center">
  <%= link_to_next_page @entries, 'load more', remote: true,
                        class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>
</div>
<br>
<br>

app/views/pages/terms.html.erb
<p></p>
<h5 class="text-secondary">Terms of Service</h5>
<hr class="custom-horizontal">

<p class="text-normal">
  Elaka offers <%= link_to "elaka.io", root_path, class: "text-yellow text-decoration-none" %>
  (the "Website") according to the Terms of Service declared below. We are not a registered company yet, but we
  reserve the right to revise these terms from time to time. We will post a notice of any material revisions on
  the Website. Your continued usage of the Website constitutes your acceptance of these terms,
  available at <%= link_to "www.elaka.io/terms", terms_path, class: "text-yellow text-decoration-none" %>
  Questions about the Terms of Service may be sent to this address:
  <a class="text-yellow text-decoration-none" href = "mailto: osho@elaka.io">osho@elaka.io</a>
</p>

<h2 class="text-yellow">Usage Terms</h2>
<hr class="custom-horizontal">
<p class="text-normal">
  The Website is not suitable for all audiences. Its content is frequently presented in a coarse and direct manner
  that some may find offensive. If you do not consider yourself an appropriate user or are offended, please do not
  visit the Website.
</p>
<p class="text-normal">
  The Website is not intended for children under 13. By using the Website, you are representing that you are at
  least 18, or that you are at least 13 years old and have your parents’ permission to use the Website.
</p>
<p class="text-normal">
  You may not use the Website for any illegal activity or to violate laws in your jurisdiction.
</p>
<p class="text-normal">
  You may not exploit the Website to access unauthorized information.
</p>
<p class="text-normal">
  Elaka reserves the right to modify, suspend, or discontinue the Website for any reason, with or without notice.
</p>
<p class="text-normal">
  The Website is provided "as is" and "as available". You assume complete responsibility and risk for your use of
  the Website. Elaka does not warrant that (i) the Website will meet your requirements, (ii) you will be satisfied
  with the Website, (iii) you will at all times be able to use the Website, (iv) the Website will be without errors,
  (v) or that any errors will be corrected.
</p>
<p class="text-normal">
  Elaka is not responsible for any damages or loss resulting from your use of the Website.
</p>
<p class="text-normal">
  Elaka is not liable for any damages or losses resulting from the Website transmitting information
  such as personal messages over unencrypted networks such as email.
</p>
<p class="text-normal">
  Any failure of Elaka to enforce or exercise a right provided in these terms is not a waiver of that right.
</p>
<p class="text-normal">
  Should any provision of this Terms of Service be found invalid or unenforceable, the remaining terms shall still apply.
</p>
<p class="text-normal">
  This Terms of Service constitutes the entire agreement between you and Elaka and supersedes any and all previous
  agreements, written or oral, between you and Elaka, including previous versions of the Terms of Service.
</p>

<h2 class="text-yellow">User Conduct</h2>
<hr class="custom-horizontal">
<p class="text-normal">
  Users may not publish to the Website any words, definitions, or other information (collectively, "Content") that:
</p>
<ul class="text-normal">
  <li>
    is unlawful, threatening, libelous or defamatory;
  </li>
  <li>
    violates any party’s intellectual property; or
  </li>
  <li>
    is detrimental to the quality or intended spirit of the Website.
  </li>
</ul>

<p class="text-normal">
  Examples of unacceptable Content or behavior on the Website are those which we, in our sole discretion, determine constitute:
</p>
<ul class="text-normal">
  <li>
    abuse, harassment, threats of violence, flaming, intimidation of any person or organization, or any other threatening behavior;
  </li>
  <li>
    engaging in or contributing to any illegal activity or activity that violates others’ rights;
  </li>
  <li>
    providing information that is false, misleading or inaccurate;
  </li>
  <li>
    hacking or modifying the Website to falsely imply an association with the Elaka;
  </li>
  <li>
    implying or pretending to be affiliated with a company or organization with which you are not affiliated,
    or misrepresenting the extent of your affiliation or role with an affiliated company or organization; or
  </li>
  <li>
    disclosing personal or proprietary information of another user, person or organization.
  </li>
</ul>

<p class="text-normal">
  Elaka has the right, but not the obligation, to limit or revoke the use privileges of anyone who publishes
  unacceptable Content.
</p>

<p class="text-normal">
  At any time, Elaka may, at its sole discretion, refuse to allow Content to be published, or remove Content that
  has been published. However, Elaka is not obligated to restrict or monitor submissions in any way, or to
  block users who submit inappropriate content.
</p>

<p class="text-normal">
  By publishing Content, you represent and warrant that such Content:
</p>

<ul class="text-normal">
  <li>
    does not violate the rights of any third party, including, but not limited to, intellectual property and
    proprietary rights;
  </li>
  <li>
    is not fraudulent or and does not involve counterfeit or stolen information or items;
  </li>
  <li>
    does not violate any law, statute, ordinance or regulation; and
  </li>
  <li>
    shall not create any liability for Elaka or any of its respective parents, subsidiaries, affiliates,
    successors, assigns, employees, agents, directors, officers and shareholders, lol.
  </li>
</ul>

<p class="text-normal">
  You may not submit Content using unauthorized automated methods ("bots").
</p>

<p class="text-normal">
  Elaka does not and cannot control all Content published by third parties to the Website, and does not guarantee
  the accuracy, integrity or quality of such Content. You understand that by using the Website you may be exposed to
  Content that you may find offensive, indecent, incorrect or objectionable, and you agree that under no circumstances
  will Elaka be liable in any way for any Content, including any errors or omissions in any Content, or any loss or
  damage of any kind incurred as a result of your use of any Content. If you would like to report objectionable
  materials, you may use the "Report Translation” feature on any topic or reply. Urgent issues can be reported to this
  address: <a class="text-yellow text-decoration-none" href = "mailto: osho@elaka.io">osho@elaka.io</a>
</p>

<p class="text-normal">
  You are solely responsible for any Content you publish on the Website, and the consequences of publishing such
  Content. You agree to indemnify, defend, and hold harmless Elaka, its officers, directors, employees, and agents
  from and against any and all claims, losses, costs, liabilities, damages, judgments, penalties, interest and
  expenses (including reasonable attorneys’ fees) arising out or relating to (i) any actual or alleged breach of
  your representations, warranties, or obligations set forth in these Terms of Service, and (ii) any actual or
  alleged infringement of any intellectual property or proprietary rights by any Content or other information you
  publish to the Website.
</p>

<p class="text-normal">
  Use of the Website is also governed by our Privacy Policy, a copy of which is currently located at
  <%= link_to "www.elaka.io/privacy", privacy_path, class: "text-yellow text-decoration-none" %>
</p>

<h2 class="text-yellow">Copyright and Ownership</h2>
<hr class="custom-horizontal">
<p class="text-normal">
  Elaka owns intellectual property rights to the Website and all elements thereof, including but not limited to the
  design, artwork, functionality, and documentation. You may not copy, modify, or reverse engineer any part of the
  Website owned by Elaka.
</p>

<p class="text-normal">
  To the extent you own rights in any Content you publish on the Website, such rights shall remain yours solely
  and exclusively.
</p>

<p class="text-normal">
  When you publish Content on the Website, you grant Elaka an irrevocable, perpetual, worldwide, royalty-free,
  fully sublicenseable, non-exclusive license to copy, distribute, sell, publicly display, publicly perform
  and make derivative works of your Content on the Website, and on services affiliated with the Website and
  elsewhere (including but not limited to print, video, audio or computer media), regardless of the form of media
  used or of whether such media or services now exist or are developed in the future. By publishing Content to
  the Website, you hereby represent and warrant that you have all rights necessary to publish that Content and to grant
  the foregoing license to the Elaka. Elaka respects the intellectual property of others. It may, in appropriate
  circumstances and at its discretion, disable and/or terminate the accounts of users who repeatedly infringe
  others’ rights.
</p>

<p class="text-normal">
  If you believe that your work has been copied in a way that constitutes copyright infringement, or your intellectual
  property rights have been otherwise violated, please provide the following information to Elaka:
</p>

<ul class="text-normal">
  <li>
    an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright
    or other intellectual property interest;
  </li>
  <li>
    a description of the copyrighted work or other intellectual property that you claim has been infringed;
  </li>
  <li>
    a description of where the material that you claim is infringing is located on the site;
  </li>
  <li>
    your address, telephone number, and email address;
  </li>
  <li>
    a statement by you that you have a good faith belief that the disputed use is not authorized by the
    copyright owner, its agent, or the law; and
  </li>
  <li>
    a statement by you, made under penalty of perjury, that the above information in your notice is accurate
    and that you are the copyright or intellectual property owner or are authorized to act on the copyright or
    intellectual property owner’s behalf.
  </li>
</ul>

<p class="text-normal">
  Email me at: <a class="text-yellow text-decoration-none" href = "mailto: osho@elaka.io">osho@elaka.io</a>
</p>

<h2 class="text-yellow">Participation Disclaimer</h2>
<hr class="custom-horizontal">
<p class="text-normal">
  Elaka does not and cannot review all Content published to the Website or created by users accessing the Website,
  and is not in any manner responsible for the content of any Content or the activities of any such users.
</p>

<p class="text-normal">
  You acknowledge that by providing you with the ability to view and distribute user-generated content through
  the Website, Elaka is merely acting as a passive conduit for the distribution of such information and is
  not undertaking any obligation or liability relating to the Content or the Website users’ activities.
</p>

<p class="text-normal">
  Elaka and its respective parents, subsidiaries, affiliates, successors, assigns, employees, agents, directors,
  officers and shareholders do not undertake or assume any duty to monitor the Website for inappropriate Content.
</p>

<p class="text-normal">
  Elaka and its respective parents, subsidiaries, affiliates, successors, assigns, employees, agents, directors,
  officers and shareholders assume no responsibility or liability which may arise from the Content thereof, including,
  but not limited to, claims for defamation, libel, slander, infringement, invasion of privacy and publicity rights,
  obscenity, pornography, profanity, fraud, or misrepresentation.
</p>

<h2 class="text-yellow">Unsolicited Idea Policy</h2>
<hr class="custom-horizontal">
<p class="text-normal">
  Elaka or any of its employees or volunteers do not accept or consider unsolicited ideas, including ideas for new
  advertising campaigns, new promotions, new or improved products or technologies, product enhancements, processes,
  materials, marketing plans or new product names. Please do not submit any unsolicited ideas, original creative
  artwork, suggestions or other works ("submissions") in any form to Elaka or any of its employees. The sole purpose
  of this policy is to avoid potential misunderstandings or disputes when Elaka’s products or marketing strategies
  might seem similar to ideas submitted to Elaka. If, despite our request that you not send us your ideas,
  you still submit them, then regardless of what your letter says, the following terms shall apply to your submissions.
</p>

<h2 class="text-yellow">TERMS OF IDEA SUBMISSION</h2>
<hr class="custom-horizontal">
<p class="text-normal">
  You agree that: (1) your submissions and their contents will automatically become the property of Elaka, without any
  compensation to you; (2) Elaka may use or redistribute the submissions and their contents for any purpose and in
  any way; (3) there is no obligation for Elaka to review the submission; and (4) there is no obligation to keep any
  submissions confidential.
</p>

<h2 class="text-yellow">Feedback and Information</h2>
<hr class="custom-horizontal">
<p class="text-normal">
  Any feedback you provide at this site shall be deemed to be non-confidential. Elaka shall be free to use
  such information on an unrestricted basis.
</p>

<h2 class="text-yellow">Advertising</h2>
<hr class="custom-horizontal">
<p class="text-normal">
  We currently do not use any advertising or sale of products. Everything is partly open-source.
</p>

<h2 class="text-yellow">Updated</h2>
<hr class="custom-horizontal">
<p class="text-normal">
  Updated: February 2021
</p>

<span class="text-gray">
  <%= link_to "About", about_path, class: "text-yellow text-decoration-none" %>,
  <%= link_to "Privacy", privacy_path, class: "text-yellow text-decoration-none" %>
  <span class="text-gray" style="font-size: small">© 2021</span>
</span>
<br>
<br>
<br>

app/views/pages/trending.html.erb
<!--suppress ALL -->
<br>

<h5 class="text-secondary" style="padding-bottom: 0.2em;">&#x1F525; Trending</h5>

<!-- Show trending results -->
<div id="trending-wrap">
  <% @trends.each do | entry | %>
    <%= render 'entries/entry', entry: entry %>
    <br>
  <% end %>
</div>
<div id="trending-load-more" class="text-center">
  <%= link_to_next_page @trends, 'load more', remote: true,
                        class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>
</div>
<br>
<br>

app/views/pages/trending.js.erb
$("#trending-wrap").append("<%=j render 'pages/hot' %>")
$("#trending-load-more").html("<%=j link_to_next_page @trends, 'load more', remote: true,
                                   class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>")

app/views/pages/users.html.erb
<!--suppress ALL -->
<br>
<%= search_form_for @search, url: users_path do |f|%>
  <div class="form-group">
    <div class="field">
      <div class="input-group">
        <%= f.search_field :username_cont, class: "form-control session-form password-format-input",
                           placeholder: "konga / search" %>
        <button class="input-group-text toggle-password-btn bg-white" id="search-button" type="submit">
          <i class="bi bi-search" aria-hidden="true"></i>
        </button>
      </div>
    </div>
  </div>
<% end %>

<!-- Show search results -->
<% if @users.count > 10 %>
  <% filter = "More than 10 users found" %>
<% else %>
  <% filter = pluralize(@users.count, "user") + " found" %>
<% end %>
<p class="text-secondary"><%= filter %></p>

<hr class="custom-horizontal">
<table class="table table-custom table-hover text-gray">
  <thead>
  <tr style="font-weight: normal;">
    <th class="border-0" style="font-weight: normal;" scope="col">Username</th>
    <th class="border-0 text-center" style="font-weight: normal;" scope="col">Entries</th>
    <th class="border-0 text-right" style="font-weight: normal;" scope="col">Joined</th>
  </tr>
  </thead>
  <tbody id="users-wrap">
  <% @users.each do | user | %>
    <% unless user.confirmed_at.blank? or user.username.blank? %>
      <%= render 'pages/users', user: user %>
    <% end %>
  <% end %>
  </tbody>
</table>
<div id="users-load-more" class="text-center">
  <%= link_to_next_page @users, 'load more', remote: true,
                        class: "text-secondary p-2 rounded btn-outline-dark text-decoration-none"%>
</div>
<br>